//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDetail
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string BankAccNo { get; set; }
        public string IFSCCode { get; set; }
        public string MICRNo { get; set; }
        public string PANNO { get; set; }
        public int BankDetails_Person { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
