//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        public Family()
        {
            this.NomineeRelativesSets = new HashSet<NomineeRelativesSet>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string FamilyMemberName { get; set; }
        public string Relation { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public int Family_Person { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<NomineeRelativesSet> NomineeRelativesSets { get; set; }
    }
}
