//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string MedicalCatagory { get; set; }
        public string MedicalRemarks { get; set; }
        public string MedicalReferance { get; set; }
        public string MedicalCertificateNo { get; set; }
        public Nullable<System.DateTime> MedicalCertificateDate { get; set; }
        public Nullable<System.DateTime> MedicalReferanceDate { get; set; }
        public int Medical_Person { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
