//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nominee
    {
        public Nominee()
        {
            this.NomineeRelativesSets = new HashSet<NomineeRelativesSet>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string Witness1 { get; set; }
        public Nullable<int> PFNo1 { get; set; }
        public string Designation1 { get; set; }
        public string Witness2 { get; set; }
        public Nullable<int> PFNo2 { get; set; }
        public string Designation2 { get; set; }
        public int Nominee_Person { get; set; }
    
        public virtual ICollection<NomineeRelativesSet> NomineeRelativesSets { get; set; }
        public virtual Person Person { get; set; }
    }
}
