//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Advances = new HashSet<Advance>();
            this.Awards = new HashSet<Award>();
            this.BankDetails = new HashSet<BankDetail>();
            this.Families = new HashSet<Family>();
            this.Increments = new HashSet<Increment>();
            this.Medicals = new HashSet<Medical>();
            this.Nominees = new HashSet<Nominee>();
            this.Penalties = new HashSet<Penalty>();
            this.PresentDetails = new HashSet<PresentDetail>();
            this.PRTFs = new HashSet<PRTF>();
            this.Trainings = new HashSet<Training>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string FullName { get; set; }
        public int PFNo { get; set; }
        public string EmplopyeeOldName { get; set; }
        public string FHName { get; set; }
        public string PresentAddress { get; set; }
        public string PermanantAddress { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfRetirement { get; set; }
        public string Religion { get; set; }
        public string Community { get; set; }
        public string Caste { get; set; }
        public string Gender { get; set; }
        public string Recruitment { get; set; }
        public string Education { get; set; }
        public string AdditionalEducation { get; set; }
        public string IdentificationMark { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<Advance> Advances { get; set; }
        public virtual ICollection<Award> Awards { get; set; }
        public virtual ICollection<BankDetail> BankDetails { get; set; }
        public virtual ICollection<Family> Families { get; set; }
        public virtual ICollection<Increment> Increments { get; set; }
        public virtual ICollection<Medical> Medicals { get; set; }
        public virtual ICollection<Nominee> Nominees { get; set; }
        public virtual ICollection<Penalty> Penalties { get; set; }
        public virtual ICollection<PresentDetail> PresentDetails { get; set; }
        public virtual ICollection<PRTF> PRTFs { get; set; }
        public virtual ICollection<Training> Trainings { get; set; }
    }
}
