//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresentDetail
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string Department { get; set; }
        public string Scale { get; set; }
        public string Group { get; set; }
        public string BillUnit { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> RateOfPay { get; set; }
        public string Station { get; set; }
        public int PresentDetail_Person { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
